Added a check preventing from opening two rifts by the same user
Twentysix26/26-Cogs pull request #42
Opened 2018-11-08 10:51 UTC by DevilXD

Also fixed an issue with uppercase channel names in the message

2018-11-08 10:54 UTC, DevilXD commented
Previously, you could open two rifts that would overwrite each other in the open_rifts dict, breaking the connection. This check prevents the user from opening up a second rift without closing the first one first, with a proper response message.

Also fixed a small issue where entering channel names with uppercase letters in them would yield no results.

2018-11-11 15:22 UTC, Twentysix26 requested changes
I don't like the limit of one rift per user though. And you're right, the connection will partially break if two rifts are opened.  
Mind using author.id + channel.id as the key for `open_rift`? That should do it

2018-11-11 15:22 UTC, Twentysix26 commented on rift/rift.py
> +        self.open_rifts[author] = OpenRift(source=author_channel, destination=channel)
```suggestion
        self.open_rifts[author.id + channel.id] = OpenRift(source=author_channel, destination=channel)
```
This will allow multiple rifts for the same user. Of course this change needs to be applied in each instance in which `self.open_rifts` is used.

2018-11-11 18:39 UTC, DevilXD commented
Should be working as requested now.

2018-11-13 20:33 UTC, merged